### ISSUE TITLE
Umbrella Ticket

### ISSUE THREAD

**Issue by lim04francis** [NiharMarar/p4lavalamps#18]
Group Tickets (Progress Technicals found on each individual Ticket)

- [x] [Luca Pinto - Week 3 Ticket](https://github.com/NiharMarar/p4lavalamps/issues/17): Make website look better/ more organized 
- [x] [Nihar Marar - Ticket 3](https://github.com/NiharMarar/p4lavalamps/issues/16): Add a news api and make add to the database
- [x] [Colin Tran - Week 3 Ticket](https://github.com/NiharMarar/p4lavalamps/issues/14): Deploy with online pi and get runtime link.
- [x] [Francis Lim - Week 3](https://github.com/NiharMarar/p4lavalamps/issues/3): Develop and integrate group theme on all subpages and clean up/make sure there are four interactions
- [x] [Ticket #3: Bryce Modugno](https://github.com/NiharMarar/p4lavalamps/issues/19): styling, html pages, contributions to new API page

Final Project Requirements
+5 Theme Section (No Login or Easy Guest access)
You must have a Group Project and/or Theme.  Four (4) key interactions are expected.
Data Driven page(s). Technical evaluation expectations require data on Theme pages to be driven by backend, Jinja and usage of Class code in front.  DB code or Web APIs are viable options for this requirement.  A mix of backend usage is ATTRACTIVE to Teacher.
Something fun for user to do or for user to interact with or user learn from your site.

+5 Individual Section
Individual Section... All projects have an area where individuals have built their own room in site (aka Mini Labs and Digital Portfolio)
Code Modeling... Code structure will include BluePrint organization for Individual Areas.
Individual rooms should retain theme of site and navigation of site.  It should be easy to navigate into and out of room without losing orientation.

+5 API Section
Code Requirement... You need to have endpoint(s) working through a REST API.   
Crossover sharing of REST API with another project team. Endpoint is required for crossover.
An area where you can see usage of an REST API endpoint from another team.  This should be easy to navigate into and out of area which presents this code.  Making updates to remote site is HIGHLY encouraged.

+5 Deployment. Section
How it is made.  An Area where you can see embedded content that describes 'how it was made'.   ie "Readme', 'Scrum Board', Code embed(s).
You must Deploy to Teacher provided hardware and be a part of N@tM requirements.
Quality and Usability of Project
